---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ditvtvtvt/users:0.x
    argocd-image-updater.argoproj.io/users.ignore-tags: '*'
    argocd-image-updater.argoproj.io/users.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: users-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: replicaCount
        value: '2'
      - name: image.repository
        value: ditvtvtvt/users
      - name: image.tag
        value: 0.1.1
      - name: service.port
        value: '8080'
      - name: livenessProbe.httpGet.path
        value: /healthz
      - name: readinessProbe.httpGet.path
        value: /healthz
    path: helm-charts/users
    repoURL: ssh://git@github.com/DITVTVTVT/k8s.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
