helm:
  parameters:
  - name: replicaCount
    value: "2"
    forcestring: false
  - name: image.repository
    value: ditvtvtvt/payments
    forcestring: false
  - name: image.tag
    value: 2.5.1
    forcestring: true
  - name: service.port
    value: "8080"
    forcestring: false
  - name: livenessProbe.httpGet.path
    value: /healthz
    forcestring: false
  - name: readinessProbe.httpGet.path
    value: /healthz
    forcestring: false
  - name: image.name
    value: ditvtvtvt/payments
    forcestring: true
