---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: payments-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ssh://git@github.com/DITVTVTVT/k8s.git
    targetRevision: main
    path: helm-charts/payments
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: "ditvtvtvt/payments"
        - name: "image.tag"
          value: "0.1.1"
        - name: "service.port"
          value: "8080"
        - name: "livenessProbe.httpGet.path"
          value: "/healthz"
        - name: "readinessProbe.httpGet.path"
          value: "/healthz"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true